### ISSUE TITLE
Android Crash。com.facebook.react.common.JavascriptException: null is not an object (evaluating 'v.registerApp')

### ISSUE THREAD

**Issue by xclidongbo** [react-native-community/discussions-and-proposals#688]
Android Crash。

```
2023-07-17 16:06:31.125 16484-16608/? E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.JavascriptException: null is not an object (evaluating 'v.registerApp'), stack:
    <unknown>@1009:2226
    h@2:1670
    <unknown>@1008:279
    h@2:1670
    <unknown>@762:534
    h@2:1670
    <unknown>@761:240
    h@2:1670
    <unknown>@11:70
    h@2:1670
    d@2:868
    global code@1038:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:49)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
    
    
    --------- beginning of crash
2023-07-17 16:06:31.125 16484-16608/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.sinosig.meoa.app, PID: 16484
    com.facebook.react.common.JavascriptException: null is not an object (evaluating 'v.registerApp'), stack:
    <unknown>@1009:2226
    h@2:1670
    <unknown>@1008:279
    h@2:1670
    <unknown>@762:534
    h@2:1670
    <unknown>@761:240
    h@2:1670
    <unknown>@11:70
    h@2:1670
    d@2:868
    global code@1038:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:49)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).
