### ISSUE TITLE
React Native 0.76.3 build issue in Android :java.lang.UnsatisfiedLinkError: dlopen failed: library "libreact_devsupportjni.so" not found

### ISSUE THREAD

**Issue by Narigara007** [react-native-community/discussions-and-proposals#837]
### Introduction

**React Native 0.76.3 build issue in Android** 

### Details
**I'm getting below errors while doing build from Android Studio using react native version 0.76.3**

React Native 0.76.3 build issue in Android :java.lang.UnsatisfiedLinkError: dlopen failed: library "libreact_devsupportjni.so" not found

FATAL EXCEPTION: AsyncTask #2
                                                                                                    Process: com.abc.android.dev, PID: 31352
                                                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                    	at android.os.AsyncTask$4.done(AsyncTask.java:415)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
                                                                                                    	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreact_devsupportjni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
                                                                                                    	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
                                                                                                    	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:812)
                                                                                                    	at com.facebook.react.devsupport.DevSupportSoLoader.staticInit(DevSupportSoLoader.kt:21)
                                                                                                    	at com.facebook.react.devsupport.InspectorFlags.<clinit>(InspectorFlags.kt:16)
                                                                                                    	at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:216)
                                                                                                    	at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:213)
                                                                                                    	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
2024-12-02 11:12:16.244   522-1816  ActivityManager         system_server                        I  Flag disabled. Ignoring finishAttachApplication from uid: 10200. pid: 31352

### Discussion points

Team, Can you please help me to fix on this issue, please?

**Comment by cortinico** [comment]
This is not the right repo to report those kind of issues.
You should either:
1. Open an issue here **and** provide a reproducer: https://github.com/facebook/react-native
2. Ask your question on stackoverflow https://stackoverflow.com/questions/tagged/react-native

**Comment by gokulananth0802** [comment]
@Narigara007 Have you cleared this error, me too getting the same error

**Comment by evilbinary** [comment]
def jscFlavor = 'io.github.react-native-community:jsc-android:2026004.+'
